client_config_backend: settings
client_config:
  client_id: 847316405643-7vtg49ts7qk2j3fa3dgl3ctdisuruice.apps.googleusercontent.com
  client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install